(()=>{
  const DATA=window.CALITO_OPERATIONAL_MEMORY||{};
  const FORM=DATA.questionario_transicao||{};
  const KEY='calito:transicao:respostas:v1';
  const ENDPOINT=window.CALITO_FORM_ENDPOINT||'';
  const SUBMIT_KEY=window.CALITO_FORM_SUBMIT_KEY||'';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"respostas":{},"meta":{}}')}catch{return {respostas:{},meta:{}}}};
  const save=v=>localStorage.setItem(KEY,JSON.stringify(v));
  const clear=()=>localStorage.removeItem(KEY);
  function ensureStyles(){if(document.getElementById('transicao-style'))return;const s=document.createElement('style');s.id='transicao-style';s.textContent=`.transicao-modal{position:fixed;inset:0;background:rgba(17,24,39,.62);display:none;align-items:flex-start;justify-content:center;padding:28px 14px;overflow:auto;z-index:999}.transicao-modal.open{display:flex}.transicao-card{width:min(860px,100%);background:#fff;border-radius:24px;padding:26px;box-shadow:0 30px 80px rgba(0,0,0,.25)}.transicao-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.transicao-head h2{margin:0 0 6px}.transicao-head p{margin:0;color:#5f6675;line-height:1.5}.transicao-close{border:0;background:#f3f4f6;border-radius:12px;padding:9px 12px;cursor:pointer}.transicao-field{margin:18px 0}.transicao-field label{display:block;font-weight:800;margin-bottom:7px}.transicao-field input,.transicao-field textarea{width:100%;border:1px solid #d9dde7;border-radius:12px;padding:12px;font:inherit}.transicao-field textarea{min-height:110px;resize:vertical}.transicao-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.transicao-actions button{border:0;border-radius:12px;padding:12px 16px;font-weight:800;cursor:pointer}.transicao-primary{background:linear-gradient(135deg,#fdc830,#f37335);color:#fff}.transicao-secondary{background:#eef2f7;color:#172033}.transicao-danger{background:#fff1f0;color:#9f2d21}.transicao-note{background:#fff7ed;border-left:4px solid #f37335;padding:12px 14px;border-radius:10px;margin:16px 0;line-height:1.5}.transicao-status{margin-top:12px;font-size:14px;color:#475569}.transicao-ok{color:#16753a;font-weight:800}.transicao-err{color:#a43d22;font-weight:800}`;document.head.appendChild(s)}
  function renderFields(saved){return (FORM.campos||[]).map(f=>`<div class="transicao-field"><label for="tr_${esc(f.id)}">${esc(f.pergunta)}${f.obrigatorio?' *':''}</label>${f.tipo==='textarea'?`<textarea id="tr_${esc(f.id)}" data-id="${esc(f.id)}" ${f.obrigatorio?'required':''}>${esc(saved.respostas?.[f.id]||'')}</textarea>`:`<input id="tr_${esc(f.id)}" data-id="${esc(f.id)}" value="${esc(saved.respostas?.[f.id]||'')}" ${f.obrigatorio?'required':''}>`}</div>`).join('')}
  function build(){ensureStyles();if(document.getElementById('transicao-modal'))return;const saved=load();const modal=document.createElement('div');modal.className='transicao-modal';modal.id='transicao-modal';modal.innerHTML=`<div class="transicao-card"><div class="transicao-head"><div><h2>${esc(FORM.titulo||'Alinhamento da transição')}</h2><p>${esc(FORM.objetivo||'Registrar seu entendimento atual da negociação.')}</p></div><button class="transicao-close" type="button">Fechar</button></div><div class="transicao-note">Responda com suas palavras. Este questionário não mostra previamente a versão de nenhuma das partes e não substitui o contrato definitivo.</div><form id="transicao-form">${renderFields(saved)}<div class="transicao-note">${esc(FORM.declaracao||'As respostas registram seu entendimento atual e serão usadas para alinhamento antes do contrato.')}</div><div class="transicao-actions"><button class="transicao-primary" id="transicao-submit" type="submit">Salvar e concluir</button><button class="transicao-secondary" id="transicao-download" type="button">Gerar cópia das respostas</button><button class="transicao-danger" id="transicao-clear" type="button">Limpar respostas</button></div><div class="transicao-status" id="transicao-status"></div></form></div>`;document.body.appendChild(modal);
    modal.querySelector('.transicao-close').onclick=()=>modal.classList.remove('open');
    modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
    const form=modal.querySelector('#transicao-form'),status=modal.querySelector('#transicao-status'),submit=modal.querySelector('#transicao-submit');
    function collect(){const data={};form.querySelectorAll('[data-id]').forEach(el=>data[el.dataset.id]=el.value.trim());return data}
    function persist(){const packet={meta:{versao:FORM.versao||1,salvo_em:new Date().toISOString(),origem:'Calito — Casa da Limpeza',tipo:'questionario_alinhamento_transicao',protocolo:(crypto.randomUUID?.()||String(Date.now()))},respostas:collect()};save(packet);return packet}
    form.addEventListener('input',()=>{const packet={meta:{...(load().meta||{}),rascunho_em:new Date().toISOString()},respostas:collect()};save(packet)});
    form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const packet=persist();if(!ENDPOINT||!SUBMIT_KEY){status.className='transicao-status transicao-err';status.textContent='Envio automático ainda não está habilitado. Avise o responsável pela plataforma.';return}submit.disabled=true;status.className='transicao-status';status.textContent='Registrando suas respostas...';try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json','x-calito-submit-key':SUBMIT_KEY},body:JSON.stringify(packet)});const out=await r.json().catch(()=>({}));if(!r.ok||!out.ok)throw new Error(out.error||'save_failed');packet.meta.enviado_em=new Date().toISOString();packet.meta.protocolo_servidor=out.protocolo||'';packet.meta.caminho_servidor=out.path||'';save(packet);status.className='transicao-status transicao-ok';status.textContent='Concluído. Suas respostas foram registradas com segurança. Protocolo: '+(out.protocolo||'registrado')+'. Você já pode avisar que terminou.'}catch(err){status.className='transicao-status transicao-err';status.textContent='Não foi possível registrar agora. Suas respostas continuam salvas neste navegador. Tente novamente em alguns instantes.'}finally{submit.disabled=false}});
    modal.querySelector('#transicao-download').onclick=()=>{if(!form.reportValidity())return;const packet=persist();const blob=new Blob([JSON.stringify(packet,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ALINHAMENTO_TRANSICAO_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);status.className='transicao-status';status.textContent='Cópia local gerada.'};
    modal.querySelector('#transicao-clear').onclick=()=>{if(!confirm('Limpar todas as respostas salvas neste navegador?'))return;clear();form.reset();status.className='transicao-status';status.textContent='Respostas locais apagadas.'};
  }
  function open(){build();document.getElementById('transicao-modal').classList.add('open')}
  function addButton(){const quick=document.querySelector('.quick');if(!quick||document.getElementById('btn-alinhamento'))return;const b=document.createElement('button');b.id='btn-alinhamento';b.type='button';b.textContent='Alinhamento da transição';b.onclick=open;quick.appendChild(b)}
  build();addButton();window.CALITO_SKILLS=window.CALITO_SKILLS||{};window.CALITO_SKILLS['alinhamento-transicao']={version:'2.0.0',status:'ativo',open};
})();