(()=>{
  const DATA=window.CALITO_OPERATIONAL_MEMORY||{};
  const STORE_KEY='calito:inteligencia-loja:decision:v2';
  const months={janeiro:1,fevereiro:2,marco:3,abril:4,maio:5,junho:6,julho:7,agosto:8,setembro:9,outubro:10,novembro:11,dezembro:12};
  const clean=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
  const pct=v=>num(v)+'%';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  const getState=()=>{try{return JSON.parse(sessionStorage.getItem(STORE_KEY)||'null')}catch{return null}};
  const setState=s=>sessionStorage.setItem(STORE_KEY,JSON.stringify(s));
  const clearState=()=>sessionStorage.removeItem(STORE_KEY);

  function add(text){const chat=document.getElementById('chat');if(!chat)return;const row=document.createElement('div');row.className='message';row.innerHTML='<div class="avatar">C</div><div><div class="bubble"></div><div class="meta">Calito · skill Inteligência da Loja</div></div>';row.querySelector('.bubble').innerHTML=text;chat.appendChild(row);row.scrollIntoView({behavior:'smooth',block:'end'});}
  function addUser(text){const chat=document.getElementById('chat');if(!chat)return;const row=document.createElement('div');row.className='message user';row.innerHTML='<div class="avatar">V</div><div><div class="bubble"></div><div class="meta">Você · agora</div></div>';row.querySelector('.bubble').textContent=text;chat.appendChild(row);}
  function table(rows,cols){return '<div class="table-wrap"><table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+c[1](r)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
  function monthFrom(s){s=clean(s);for(const [n,m] of Object.entries(months))if(s.includes(n))return m;return null;}
  function rowsForMonth(m){return (DATA.produto_mes||[]).filter(r=>Number(r.mes)===m);}
  function aggregateRows(rows){const map=new Map();for(const r of rows){const k=r.codigo||r.produto;const x=map.get(k)||{codigo:k,produto:r.produto,categoria:r.categoria,quantidade:0,faturamento:0,custo:0,lucro:0,meses:new Set(),anos:new Set()};x.quantidade+=Number(r.quantidade||0);x.faturamento+=Number(r.faturamento||0);x.custo+=Number(r.custo||0);x.lucro+=Number(r.lucro_bruto||0);x.meses.add(r.periodo);x.anos.add(r.ano);map.set(k,x)}return [...map.values()].map(x=>({...x,margem:x.faturamento?x.lucro/x.faturamento*100:0,recorrencia:x.anos.size}));}
  function score(p){const rev=Math.log10(Math.max(1,p.faturamento));const qty=Math.log10(Math.max(1,p.quantidade));const margin=Math.max(0,Math.min(100,p.margem))/100;const recurrence=Math.min(1,p.recorrencia/3);return rev*.38+qty*.24+margin*1.2+recurrence*.8;}
  function priorityLabel(p,maxScore){const s=score(p)/(maxScore||1);if(s>=.78)return '🟢 Reforçar';if(s>=.58)return '🟡 Manter forte';if(s>=.38)return '🟠 Comprar com cautela';return '🔴 Baixa prioridade histórica';}
  function historicalMonth(m){const agg=aggregateRows(rowsForMonth(m));if(!agg.length)return null;const ranked=agg.sort((a,b)=>score(b)-score(a));const max=score(ranked[0]);return ranked.map(p=>({...p,prioridade:priorityLabel(p,max)}));}
  function categoriesForMonths(list){const rows=(DATA.produto_mes||[]).filter(r=>list.includes(Number(r.mes)));const map=new Map();for(const r of rows){const k=r.categoria||'Outros';const x=map.get(k)||{categoria:k,faturamento:0,lucro:0,quantidade:0};x.faturamento+=Number(r.faturamento||0);x.lucro+=Number(r.lucro_bruto||0);x.quantidade+=Number(r.quantidade||0);map.set(k,x)}return [...map.values()].map(x=>({...x,margem:x.faturamento?x.lucro/x.faturamento*100:0})).sort((a,b)=>b.faturamento-a.faturamento);}
  function findProduct(text){const n=clean(text);const candidates=(DATA.produtos||[]).filter(p=>{const pn=clean(p.produto);return n.includes(pn)||pn.includes(n)});if(candidates.length)return candidates.sort((a,b)=>String(b.produto).length-String(a.produto).length)[0];const words=n.split(/\s+/).filter(w=>w.length>=4&&!['comprar','quanto','estoque','produto','agosto','setembro','outubro','novembro','dezembro','janeiro','fevereiro','marco','abril','maio','junho','julho'].includes(w));if(!words.length)return null;return (DATA.produtos||[]).map(p=>({p,hits:words.filter(w=>clean(p.produto).includes(w)).length})).filter(x=>x.hits>=Math.min(2,words.length)).sort((a,b)=>b.hits-a.hits||Number(b.p.faturamento_total||0)-Number(a.p.faturamento_total||0))[0]?.p||null;}
  function productMonthHistory(product,m){if(!product)return null;const rows=(DATA.produto_mes||[]).filter(r=>(r.codigo===product.codigo||clean(r.produto)===clean(product.produto))&&Number(r.mes)===m);if(!rows.length)return null;const x=aggregateRows(rows)[0];const years=[...new Set(rows.map(r=>Number(r.ano)))].sort();const avgQty=x.quantidade/Math.max(1,years.length);const avgSales=x.faturamento/Math.max(1,years.length);return {...x,anos:years,media_quantidade:avgQty,media_faturamento:avgSales};}
  function firstNumber(text){const m=String(text).replace(/\./g,'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null;}
  function parseYesNo(text){const n=clean(text);if(/\b(nao|nenhum|nenhuma|zero|nada)\b/.test(n))return false;if(/\b(sim|tem|tenho|existe|ha|há)\b/.test(n))return true;return null;}
  function parseField(field,text){const n=clean(text),v=firstNumber(text);if(field==='estoque_atual')return v;
    if(field==='transito'){const yn=parseYesNo(text);if(yn===false)return 0;return v;}
    if(field==='prazo_fornecedor_dias'){if(/pronta entrega|imediat/.test(n))return 0;return v;}
    if(field==='pedido_minimo'){const yn=parseYesNo(text);if(yn===false)return 1;return v;}
    if(field==='custo_atual'||field==='preco_venda_atual'||field==='estoque_maximo')return v;
    return v;}
  const fieldQuestions={
    estoque_atual:s=>`Qual é o <b>estoque atual</b> de ${esc(s.produto_nome)}? Pode responder só com a quantidade.`,
    transito:s=>`Existe mercadoria de <b>${esc(s.produto_nome)}</b> já comprada/em trânsito? Se sim, quantas unidades?`,
    prazo_fornecedor_dias:s=>`Qual é o <b>prazo normal do fornecedor</b> de ${esc(s.produto_nome)} em dias?`,
    pedido_minimo:s=>`Existe <b>pedido mínimo ou caixa fechada</b> para ${esc(s.produto_nome)}? Informe a quantidade mínima; se não existir, diga “não”.`,
    estoque_maximo:s=>`Existe algum <b>limite físico ou estoque máximo</b> que você quer manter para ${esc(s.produto_nome)}? Se não houver, diga “não”.`,
    custo_atual:s=>`Qual é o <b>custo atual de compra</b> de ${esc(s.produto_nome)}?`,
    preco_venda_atual:s=>`Qual é o <b>preço de venda atual</b> de ${esc(s.produto_nome)}?`
  };
  function nextMissing(state){return state.required.find(k=>state.values[k]===undefined||state.values[k]===null);}
  function askNext(state){const f=nextMissing(state);if(!f)return finalizeDecision(state);setState(state);return `<b>Para decidir com segurança, falta uma informação.</b><br>${fieldQuestions[f](state)}<div class="notice">Já registrado: ${state.required.filter(k=>state.values[k]!==undefined&&state.values[k]!==null).map(k=>k.replaceAll('_',' ')).join(', ')||'nenhum dado atual ainda'}.</div>`;}
  function roundLot(qty,lot){lot=Math.max(1,Number(lot||1));return Math.max(0,Math.ceil(qty/lot)*lot);}
  function finalizeDecision(state){const p=state.product,m=state.month,h=productMonthHistory(p,m);if(!h){clearState();return 'Não encontrei histórico suficiente desse produto para o mês escolhido. Posso analisar outro período ou produto.';}
    const estoque=Number(state.values.estoque_atual||0),transito=Number(state.values.transito||0),lead=Math.max(0,Number(state.values.prazo_fornecedor_dias||0)),lot=Math.max(1,Number(state.values.pedido_minimo||1));
    const monthlyAvg=Math.max(0,h.media_quantidade);const daily=monthlyAvg/30;const leadDemand=daily*lead;const safety=Math.max(monthlyAvg*.15,leadDemand*.25);const target=monthlyAvg+leadDemand+safety;const available=estoque+transito;let suggested=Math.max(0,target-available);suggested=roundLot(suggested,lot);if(state.values.estoque_maximo&&Number(state.values.estoque_maximo)>0)suggested=Math.min(suggested,Math.max(0,Number(state.values.estoque_maximo)-available));
    const coverage=daily>0?available/daily:null;const risk=available<=leadDemand?'🔴 Risco de ruptura':coverage!==null&&coverage<20?'🟠 Cobertura curta':'🟢 Cobertura razoável';
    const html=`<b>Decisão assistida — ${esc(p.produto)}</b><div class="kpis"><div class="kpi"><small>Média histórica no mês</small><b>${num(monthlyAvg)} un.</b></div><div class="kpi"><small>Disponível + trânsito</small><b>${num(available)} un.</b></div><div class="kpi"><small>Cobertura estimada</small><b>${coverage===null?'-':num(coverage)+' dias'}</b></div><div class="kpi"><small>Sugestão de reposição</small><b>${num(suggested)} un.</b></div></div><div class="notice">${risk}. Cálculo usa histórico do mês, estoque informado, mercadoria em trânsito, prazo do fornecedor, margem de segurança e lote mínimo. É recomendação operacional, não pedido automático.</div>${table([{...h}],[['Histórico do mês',x=>String(m).padStart(2,'0')],['Anos usados',x=>x.anos.join(', ')],['Qtd. histórica total',x=>num(x.quantidade)],['Faturamento histórico',x=>money(x.faturamento)],['Margem bruta',x=>pct(x.margem)]])}`;
    clearState();return html;}
  function beginDecision(raw,type='reposicao'){const product=findProduct(raw);const m=monthFrom(raw)||new Date().getMonth()+1;if(!product)return '<b>Qual produto você quer analisar?</b><div class="notice">Exemplo: “Quanto devo comprar de Pedra de Cloro Genco para agosto?”</div>';
    const base=['estoque_atual','transito','prazo_fornecedor_dias','pedido_minimo'];if(type==='excesso')base.push('estoque_maximo');if(type==='margem_atual')base.push('custo_atual','preco_venda_atual');const state={version:2,type,produto_codigo:product.codigo,produto_nome:product.produto,product,month:m,required:base,values:{},started_at:new Date().toISOString()};return askNext(state);}
  function handlePending(raw,state){const f=nextMissing(state);if(!f)return finalizeDecision(state);const value=parseField(f,raw);if(value===null||value===undefined||Number.isNaN(value)){if(/cancelar|parar|esquece|encerrar/.test(clean(raw))){clearState();return 'Decisão cancelada. Nenhum dado foi alterado.';}return `Não consegui identificar o valor de <b>${f.replaceAll('_',' ')}</b>. ${fieldQuestions[f](state)}`;}
    state.values[f]=value;return askNext(state);}
  function buyingAnswer(m){const rows=historicalMonth(m);if(!rows)return 'Não encontrei histórico suficiente para esse mês.';const top=rows.slice(0,15);return '<b>Prioridade histórica para o mês '+String(m).padStart(2,'0')+'</b><div class="notice">Use esta lista para escolher onde investigar primeiro. Para transformar prioridade em quantidade de compra, diga “quanto devo comprar de [produto]?”; eu vou perguntar estoque, trânsito, prazo e lote mínimo.</div>'+table(top,[['Produto',r=>r.produto],['Categoria',r=>r.categoria],['Qtd. hist.',r=>num(r.quantidade)],['Faturamento',r=>money(r.faturamento)],['Margem bruta',r=>pct(r.margem)],['Prioridade',r=>r.prioridade]]);}
  function anchorsAnswer(m){const rows=historicalMonth(m);if(!rows)return 'Não encontrei histórico suficiente.';return '<b>Produtos que mais sustentaram historicamente esse mês</b>'+table(rows.sort((a,b)=>b.faturamento-a.faturamento).slice(0,20),[['Produto',r=>r.produto],['Categoria',r=>r.categoria],['Faturamento',r=>money(r.faturamento)],['Quantidade',r=>num(r.quantidade)],['Lucro bruto',r=>money(r.lucro)],['Recorrência',r=>r.recorrencia+' ano(s)']]);}
  function highMarginAnswer(m){const rows=historicalMonth(m);if(!rows)return 'Não encontrei histórico suficiente.';const filtered=rows.filter(r=>r.quantidade>=10&&r.faturamento>=500).sort((a,b)=>(b.margem*.55+Math.log10(Math.max(1,b.faturamento))*10)-(a.margem*.55+Math.log10(Math.max(1,a.faturamento))*10)).slice(0,20);return '<b>Boa venda + margem bruta relevante</b><div class="notice">Filtro evita destacar margens altas em produtos com volume irrelevante.</div>'+table(filtered,[['Produto',r=>r.produto],['Qtd.',r=>num(r.quantidade)],['Faturamento',r=>money(r.faturamento)],['Lucro bruto',r=>money(r.lucro)],['Margem',r=>pct(r.margem)]]);}
  function cautionAnswer(m){const rows=historicalMonth(m);if(!rows)return 'Não encontrei histórico suficiente.';const low=rows.filter(r=>r.recorrencia<=1||r.quantidade<5).sort((a,b)=>a.faturamento-b.faturamento).slice(0,20);return '<b>Itens para cautela</b><div class="notice">Não afirmo encalhe sem estoque atual. A tabela mostra baixo giro/baixa recorrência histórica.</div>'+table(low,[['Produto',r=>r.produto],['Categoria',r=>r.categoria],['Qtd. hist.',r=>num(r.quantidade)],['Faturamento',r=>money(r.faturamento)],['Recorrência',r=>r.recorrencia+' ano(s)']]);}
  function categoriesAnswer(a,b){const list=[];for(let m=a;m<=b;m++)list.push(m);const rows=categoriesForMonths(list).slice(0,12);return '<b>Categorias mais relevantes entre os meses '+a+' e '+b+'</b>'+table(rows,[['Categoria',r=>r.categoria],['Quantidade',r=>num(r.quantidade)],['Faturamento',r=>money(r.faturamento)],['Lucro bruto',r=>money(r.lucro)],['Margem',r=>pct(r.margem)]]);}
  function marketingPerformance(){const rows=((DATA.instagram_correlations&&DATA.instagram_correlations.meses)||[]).filter(x=>x.vendas&&x.marketing);if(!rows.length)return '<div class="notice">A memória de marketing ainda não possui correlações suficientes.</div>';const best=[...rows].sort((a,b)=>Number(b.vendas.faturamento||0)-Number(a.vendas.faturamento||0)).slice(0,8);return '<b>Campanhas e períodos de maior desempenho comercial</b><div class="notice">É associação temporal; não comprova que a campanha causou a venda.</div>'+table(best,[['Período',r=>r.periodo],['Posts',r=>num(r.marketing.total_publicacoes)],['Reels',r=>num(r.marketing.total_reels)],['Faturamento',r=>money(r.vendas.faturamento)],['Margem',r=>pct(r.vendas.margem)]]);}
  function scenarioGuide(){return '<b>Inteligência da Loja — situações que consigo apoiar</b><br>• compra e reposição com entrevista de dados atuais;<br>• risco de ruptura e cobertura;<br>• excesso/baixo giro com cautela;<br>• sazonalidade e produtos âncora;<br>• margem e relevância econômica;<br>• fornecedor com prazo longo e lote mínimo;<br>• categorias em crescimento ou perda de força;<br>• campanhas x vendas por associação temporal;<br>• comparação entre meses e anos.<div class="notice">Quando a decisão exigir dado atual, eu pergunto somente o que estiver faltando antes de recomendar.</div>';}
  function matches(s){return !!getState()||/quanto.*comprar|quantas.*comprar|quanto.*repor|reposicao|reposição|risco.*ruptura|estoque baixo|estoque atual|mercadoria.*transito|mercadoria.*trânsito|prazo.*fornecedor|pedido minimo|pedido mínimo|excesso.*estoque|estoque.*excesso|o que devo comprar|o que comprar|reforcar|reforçar|estoque maior|prioridade de compra|sustentaram|sustenta.*mes|boa venda.*margem|margem alta.*venda|encalh|cautela|baixa prioridade|inteligencia da loja|inteligência da loja|calendario comercial|calendário comercial|categorias.*cres|campanhas.*melhor resultado/.test(s);}
  function answer(raw){const pending=getState();if(pending)return handlePending(raw,pending);const n=clean(raw),m=monthFrom(n);if(/quanto.*comprar|quantas.*comprar|quanto.*repor|reposicao|reposição|risco.*ruptura|estoque baixo/.test(n))return beginDecision(raw,'reposicao');if(/excesso.*estoque|estoque.*excesso|encalh.*quanto/.test(n))return beginDecision(raw,'excesso');if(/campanhas.*melhor resultado/.test(n))return marketingPerformance();if(/categorias.*cres|setembro.*novembro/.test(n))return categoriesAnswer(9,11);if(/encalh|cautela|baixa prioridade/.test(n))return cautionAnswer(m||new Date().getMonth()+1);if(/boa venda.*margem|margem alta.*venda/.test(n))return highMarginAnswer(m||new Date().getMonth()+1);if(/sustentaram|sustenta.*mes/.test(n))return anchorsAnswer(m||new Date().getMonth()+1);if(/o que devo comprar|o que comprar|reforcar|reforçar|estoque maior|prioridade de compra/.test(n))return buyingAnswer(m||new Date().getMonth()+1);if(/calendario comercial|calendário comercial/.test(n))return buyingAnswer(m||new Date().getMonth()+1);if(/inteligencia da loja|inteligência da loja/.test(n))return scenarioGuide();return null;}

  const form=document.getElementById('form');if(form){form.addEventListener('submit',e=>{const input=document.getElementById('question');const raw=input&&input.value.trim();const s=clean(raw);if(!raw||!matches(s))return;e.preventDefault();e.stopImmediatePropagation();addUser(raw);input.value='';setTimeout(()=>add(answer(raw)),100);},true);}
  window.CALITO_SKILLS=window.CALITO_SKILLS||{};window.CALITO_SKILLS['inteligencia-da-loja']={version:'2.0.0',status:'ativo',modo:'gestor-conversacional',clearDecision:clearState};
})();