(()=>{
  const DATA=window.CALITO_OPERATIONAL_MEMORY||{};
  const SMART=DATA.calito_smart||{};
  const KEY='calito:smart-transition:v1';
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
  function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
  function mergedChecklist(){const local=state();return (SMART.checklist||[]).map(i=>({...i,status:local[i.id]||i.status}))}
  function progress(items){if(!items.length)return 0;const pts={concluido:1,em_andamento:.5,pendente:0};return Math.round(items.reduce((a,i)=>a+(pts[i.status]||0),0)/items.length*100)}
  function ensureStyles(){if(document.getElementById('smart-transition-style'))return;const s=document.createElement('style');s.id='smart-transition-style';s.textContent=`.smart-modal{position:fixed;inset:0;background:rgba(15,23,42,.65);display:none;align-items:flex-start;justify-content:center;padding:24px 12px;overflow:auto;z-index:1000}.smart-modal.open{display:flex}.smart-card{width:min(980px,100%);background:#fff;border-radius:24px;padding:24px;box-shadow:0 30px 80px rgba(0,0,0,.3)}.smart-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.smart-close{border:0;background:#eef2f7;border-radius:12px;padding:9px 12px;cursor:pointer}.smart-grid{display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:10px;margin:16px 0}.smart-kpi{border:1px solid #e5e7eb;border-radius:14px;padding:13px;background:#fffaf0}.smart-kpi small{display:block;color:#6b7280}.smart-kpi b{font-size:19px}.smart-progress{height:12px;background:#edf2f7;border-radius:999px;overflow:hidden}.smart-progress span{display:block;height:100%;background:linear-gradient(135deg,#fdc830,#f37335)}.smart-list{display:grid;gap:9px;margin-top:15px}.smart-item{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;border:1px solid #e6e8ee;border-radius:14px;padding:12px}.smart-item select{border:1px solid #d5d9e3;border-radius:10px;padding:8px;background:#fff}.smart-section{margin-top:22px}.smart-note{background:#fff7ed;border-left:4px solid #f37335;padding:12px 14px;border-radius:10px;line-height:1.5}@media(max-width:720px){.smart-grid{grid-template-columns:repeat(2,1fr)}.smart-item{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function build(){ensureStyles();if(document.getElementById('smart-transition-modal'))return;const modal=document.createElement('div');modal.id='smart-transition-modal';modal.className='smart-modal';modal.innerHTML='<div class="smart-card"></div>';document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});render()}
  function render(){const modal=document.getElementById('smart-transition-modal');if(!modal)return;const items=mergedChecklist(),p=progress(items),paid=(SMART.pagamentos?.entrada_confirmada||0);modal.querySelector('.smart-card').innerHTML=`<div class="smart-head"><div><h2>${esc(SMART.titulo||'Calito Smart')}</h2><p>Transição assistida de Ariane e João na Casa da Limpeza.</p></div><button class="smart-close" type="button">Fechar</button></div><div class="smart-grid"><div class="smart-kpi"><small>Valor total</small><b>${money(SMART.valor_total)}</b></div><div class="smart-kpi"><small>Entrada confirmada</small><b>${money(paid)}</b></div><div class="smart-kpi"><small>Posse</small><b>14/07/2026</b></div><div class="smart-kpi"><small>Progresso</small><b>${p}%</b></div></div><div class="smart-progress"><span style="width:${p}%"></span></div><div class="smart-section"><h3>Checklist da transição</h3><div class="smart-list">${items.map(i=>`<div class="smart-item"><div><b>${esc(i.titulo)}</b></div><select data-id="${esc(i.id)}"><option value="pendente" ${i.status==='pendente'?'selected':''}>Pendente</option><option value="em_andamento" ${i.status==='em_andamento'?'selected':''}>Em andamento</option><option value="concluido" ${i.status==='concluido'?'selected':''}>Concluído</option></select></div>`).join('')}</div></div><div class="smart-section"><h3>Suporte de transição</h3><div class="smart-note">Luciana presta apoio inicial até 14/08/2026 e permanece disponível remotamente para dúvidas. Após essa data, Ariane, João e Luciana poderão combinar livremente eventual continuidade profissional.</div></div><div class="smart-section"><h3>Calito</h3><div class="smart-note">O suporte Calito Smart está incluído até 31/12/2026. Depois disso, personalização, manutenção ou assinatura dependem de novo acordo entre as partes.</div></div><div class="smart-section"><h3>Não concorrência</h3><div class="smart-note">A restrição se limita ao município de Antônio Carlos/SC e não alcança os demais municípios, que permanecem em comércio aberto.</div></div>`;modal.querySelector('.smart-close').onclick=()=>modal.classList.remove('open');modal.querySelectorAll('select[data-id]').forEach(sel=>sel.onchange=()=>{const x=state();x[sel.dataset.id]=sel.value;save(x);render()})}
  function open(){build();render();document.getElementById('smart-transition-modal').classList.add('open')}
  function addButton(){const quick=document.querySelector('.quick');if(!quick||document.getElementById('btn-smart-transition'))return;const b=document.createElement('button');b.id='btn-smart-transition';b.type='button';b.textContent='Calito Smart';b.onclick=open;quick.appendChild(b)}
  build();addButton();window.CALITO_SKILLS=window.CALITO_SKILLS||{};window.CALITO_SKILLS['calito-smart-transition']={version:'1.0.0',status:'ativo',open};
})();