(()=>{
const DATA=window.CALITO_OPERATIONAL_MEMORY||{};
const clean=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const months={janeiro:1,fevereiro:2,marco:3,abril:4,maio:5,junho:6,julho:7,agosto:8,setembro:9,outubro:10,novembro:11,dezembro:12};
const monthNames={1:'janeiro',2:'fevereiro',3:'março',4:'abril',5:'maio',6:'junho',7:'julho',8:'agosto',9:'setembro',10:'outubro',11:'novembro',12:'dezembro'};
const rows=()=>DATA.produto_mes||[];
function add(text){const chat=document.getElementById('chat');if(!chat)return;const row=document.createElement('div');row.className='message';row.innerHTML='<div class="avatar">C</div><div><div class="bubble"></div><div class="meta">Calito · consulta filtrada</div></div>';row.querySelector('.bubble').innerHTML=text;chat.appendChild(row);row.scrollIntoView({behavior:'smooth',block:'end'});}
function addUser(text){const chat=document.getElementById('chat');if(!chat)return;const row=document.createElement('div');row.className='message user';row.innerHTML='<div class="avatar">V</div><div><div class="bubble"></div><div class="meta">Você · agora</div></div>';row.querySelector('.bubble').textContent=text;chat.appendChild(row);}
function table(rs,cols){return '<div class="table-wrap"><table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rs.map(r=>'<tr>'+cols.map(c=>'<td>'+c[1](r)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function monthFrom(s){const n=clean(s);for(const [k,v] of Object.entries(months))if(n.includes(k))return v;return null;}
function yearsFrom(s){return [...String(s).matchAll(/\b(20\d{2})\b/g)].map(x=>Number(x[1]));}
function availableYears(){return [...new Set(rows().map(r=>Number(r.ano)).filter(Boolean))].sort((a,b)=>a-b);}
function categoryFrom(s){const n=clean(s);const cats=[...new Set(rows().map(r=>r.categoria).filter(Boolean))];const direct=cats.filter(c=>n.includes(clean(c)));if(direct.length)return direct.sort((a,b)=>b.length-a.length)[0];const aliases={piscina:['piscina','piscinas','cloro','tratamento de piscina'],lavanderia:['lavanderia','roupa','roupas'],['Aromas e bem-estar']:['aroma','aromas','aromatizante','perfumaria'],['Panos e microfibras']:['pano','panos','microfibra','microfibras'],['Mops, vassouras e equipamentos']:['mop','mops','vassoura','vassouras','equipamentos']};for(const [cat,words] of Object.entries(aliases))if(words.some(w=>n.includes(clean(w)))){const exact=cats.find(c=>clean(c)===clean(cat));if(exact)return exact;}return null;}
function aggregate(rs){const map=new Map();for(const r of rs){const k=r.codigo||r.produto;const x=map.get(k)||{produto:r.produto,categoria:r.categoria,quantidade:0,faturamento:0,lucro:0};x.quantidade+=Number(r.quantidade||0);x.faturamento+=Number(r.faturamento||0);x.lucro+=Number(r.lucro_bruto||0);map.set(k,x)}return [...map.values()].sort((a,b)=>b.faturamento-a.faturamento);}
function latestYearForMonth(m,cat){const ys=rows().filter(r=>(!m||Number(r.mes)===m)&&(!cat||clean(r.categoria)===clean(cat))).map(r=>Number(r.ano)).filter(Boolean);return ys.length?Math.max(...ys):null;}
function parseDayRange(raw){const n=clean(raw);const pat=/(\d{1,2})\s+de\s+(janeiro|fevereiro|marco|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro)(?:\s+de\s+(20\d{2}))?\s+(?:a|ate)\s+(\d{1,2})\s+de\s+(janeiro|fevereiro|marco|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro)(?:\s+de\s+(20\d{2}))?/;const m=n.match(pat);if(!m)return null;return{d1:+m[1],m1:months[m[2]],y1:m[3]?+m[3]:null,d2:+m[4],m2:months[m[5]],y2:m[6]?+m[6]:null};}
function categoryQuery(raw){const cat=categoryFrom(raw);if(!cat)return null;const m=monthFrom(raw),ys=yearsFrom(raw),range=parseDayRange(raw);if(range){return `<b>Consigo filtrar ${esc(cat)}, mas a base atual está consolidada por mês.</b><div class="notice">Não vou inventar um resultado para ${range.d1} de ${monthNames[range.m1]} a ${range.d2} de ${monthNames[range.m2]}. Para responder exatamente por dia, precisamos importar vendas com data de cada item/cupom. Hoje posso mostrar os meses completos envolvidos ou, se houver relatório diário no sistema, incorporar essa camada ao Calito.</div>`;}
let y=ys[0]||null;if(!y&&m)y=latestYearForMonth(m,cat);let rs=rows().filter(r=>clean(r.categoria)===clean(cat));if(m)rs=rs.filter(r=>Number(r.mes)===m);if(y)rs=rs.filter(r=>Number(r.ano)===y);if(!rs.length)return `<b>Não encontrei registros para ${esc(cat)}${m?' em '+monthNames[m]:''}${y?' de '+y:''}.</b>`;const agg=aggregate(rs),qty=agg.reduce((s,r)=>s+r.quantidade,0),rev=agg.reduce((s,r)=>s+r.faturamento,0),profit=agg.reduce((s,r)=>s+r.lucro,0);const period=m?`${monthNames[m]} de ${y}`:(y?String(y):'todo o histórico');const inferred=!ys.length&&m?`<div class="notice">Você não informou o ano. Usei o ano mais recente disponível para esse mês: <b>${y}</b>. Para outro ano, diga por exemplo “${monthNames[m]} de 2025”.</div>`:'';return `<b>${esc(cat)} — ${esc(period)}</b><div class="kpis"><div class="kpi"><small>Produtos diferentes</small><b>${agg.length}</b></div><div class="kpi"><small>Quantidade</small><b>${num(qty)}</b></div><div class="kpi"><small>Faturamento</small><b>${money(rev)}</b></div><div class="kpi"><small>Lucro bruto</small><b>${money(profit)}</b></div></div>${inferred}`+table(agg,[['Produto',r=>esc(r.produto)],['Quantidade',r=>num(r.quantidade)],['Faturamento',r=>money(r.faturamento)],['Lucro bruto',r=>money(r.lucro)]]) ;}
function isCategoryIntent(n){return /(liste|listar|quais|qual|o que|produtos?|itens?).*(categoria|piscina|piscinas|lavanderia|aroma|aromas|microfibra|mop|vassoura)|(categoria|piscina|piscinas|lavanderia).*(vende|vendeu|vendidos|produtos?|itens?)/.test(n);}
const form=document.getElementById('form');if(form)form.addEventListener('submit',e=>{const input=document.getElementById('question'),raw=input&&input.value.trim(),n=clean(raw);if(!raw||!isCategoryIntent(n))return;const ans=categoryQuery(raw);if(!ans)return;e.preventDefault();e.stopImmediatePropagation();addUser(raw);input.value='';setTimeout(()=>add(ans),80);},true);
window.CALITO_SKILLS=window.CALITO_SKILLS||{};window.CALITO_SKILLS['consulta-avancada']={version:'1.0.0',status:'ativo',filtros:['categoria','mes','ano','produto'],granularidade:'mensal'};
})();