name: K-OS Cloud Test Connection

on:
  push:
    branches:
      - principal  # Alinhado com a sua branch real

jobs:
  test-gcp-connection:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # OBRIGATÓRIO para o Workload Identity Federation

    steps:
    - name: Checkout do Codigo
      uses: actions/checkout@v4

    # Autenticação oficial no Google Cloud sem chaves/senhas expostas
    - name: Autenticar no Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/772534983436/locations/global/workloadIdentityPools/kos-github-pool/providers/kos-github-provider'
        service_account: 'kos-github-deployer@k-os-ultimate.iam.gserviceaccount.com'

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # Comando de teste: O GitHub vai perguntar ao GCP se o repositório Docker realmente existe ali
    - name: Validar Acesso ao Artifact Registry
      run: |
        gcloud artifacts repositories describe kos-registry --location=us-central1
        echo "======================================================================"
        echo " SUCESSO: O GitHub e a Infraestrutura do K-OS estão conectados! "
        echo "======================================================================"
